# ロール作成
CREATE ROLE mrs LOGIN
ENCRYPTED PASSWORD 'md586082399b5082acb54472ee195a57ce8'
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

# DB作成
CREATE DATABASE mrs
	WITH OWNER = mrs
		ENCODING = 'UTF8'
		TABLESPACE = pg_default
		LC_COLLATE = 'C'
		LC_CTYPE = 'C'
		TEMPLATE = template0
		CONNECTION LIMIT = -1;
		
		